num = int(input('Digite um numero inteiro'))
tabuada1 = num* 1
tabuada2 = num*2
tabuada3 = num*3
tabuada4 = num*4
tabuada5 = num*5
tabuada6 = num*6
tabuada7 = num*7
tabuada8 = num*8
tabuada9 = num*9
tabuada10 = num*10
print('{} x 1 = {}'.format(num, tabuada1))
print('{} x 2 = {}'.format(num, tabuada2))
print('{} x 3 = {}'.format(num, tabuada3))
print('{} x 4 = {}'.format(num, tabuada4))
print('{} x 5 = {}'.format(num, tabuada5))
print('{} x 6 = {}'.format(num, tabuada6))
print('{} x 7 = {}'.format(num, tabuada7))
print('{} x 8 = {}'.format(num, tabuada8))
print('{} x 9 = {}'.format(num, tabuada9))
print('{} x 10 = {}'.format(num, tabuada10))