n = input('Digite uma mensagem: ')
print('O tipo primitivo é',type(n))
print('é numérico?', n.isnumeric())
print('é alfabetico?', n.isalpha())
print('é alphanumeric?', n.isalnum())
print('é formado apenas por letras maiuscula?', n.isupper())
print('é formado apenas por letras minusculas?', n.islower())
print('é possivel imprimir?', n.isprintable())
print('Só tem espaços?', n.isspace())
